export const REFRESH_TOKEN_REPOSITORY = 'REFRESH_TOKEN_REPOSITORY';
export const USER_REPOSITORY = 'USER_REPOSITORY';
export const HOUSE_REPOSITORY = 'HOUSE_REPOSITORY';
export const ROOM_REPOSITORY = 'ROOM_REPOSITORY';
export const ITEM_REPOSITORY = 'ITEM_REPOSITORY';
export const ITEM_IMAGE_REPOSITORY = 'ITEM_IMAGE_REPOSITORY';

// Billing
export const SUBSCRIPTION_PLAN_REPOSITORY = 'SUBSCRIPTION_PLAN_REPOSITORY';
export const USER_SUBSCRIPTION_REPOSITORY = 'USER_SUBSCRIPTION_REPOSITORY';
export const CREDIT_BALANCE_REPOSITORY = 'CREDIT_BALANCE_REPOSITORY';
export const USAGE_LOG_REPOSITORY = 'USAGE_LOG_REPOSITORY';
export const CREDIT_PACK_REPOSITORY = 'CREDIT_PACK_REPOSITORY';
export const CREDIT_TRANSACTION_REPOSITORY = 'CREDIT_TRANSACTION_REPOSITORY';
