export const REFRESH_TOKEN_REPOSITORY = 'REFRESH_TOKEN_REPOSITORY';
export const USER_REPOSITORY = 'USER_REPOSITORY';
export const HOUSE_REPOSITORY = 'HOUSE_REPOSITORY';
export const ROOM_REPOSITORY = 'ROOM_REPOSITORY';
export const ITEM_REPOSITORY = 'ITEM_REPOSITORY';
export const ITEM_IMAGE_REPOSITORY = 'ITEM_IMAGE_REPOSITORY';
